# Copyright 2011 Benjamin Lee Smith <benjamin.lee.smith@gmail.com>
#
# This file is part of CafePressAPI.
# CafePressAPI is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CafePressAPI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CafePressAPI.  If not, see <http://www.gnu.org/licenses/>.

# Seriously CafePress... just return gender values for your products so I 
# don't have to do this crap. This is a mapping of merchandise to genders
module ProductGenders
  MALE = 'm'
  FEMALE = 'f'
  UNISEX = 'u' # this is basically everything that isn't male or female

  # Mapping... done by hand... from default captions and mechandiseId to genders
  PRODUCT_GENDERS = {
    '2.25" Button' => UNISEX, '118' => UNISEX,
    '2.25" Button (10 pack)' =>  UNISEX, '120' => UNISEX,
    '2.25" Button (100 pack)' =>  UNISEX, '121' => UNISEX,
    '2.25" Magnet (10 pack)' =>  UNISEX, '122' => UNISEX,
    '2.25" Magnet (100 pack)' =>  UNISEX, '123' => UNISEX,
    '21x7 Wall Peel' =>  UNISEX, '453' => UNISEX,
    '22x14 Oval Wall Peel' => UNISEX, '449' => UNISEX,
    '22x14 Wall Peel' => UNISEX, '451' => UNISEX,
    '3" Lapel Sticker (48 pk)' => UNISEX, '207' => UNISEX,
    '3.5" Button' => UNISEX, '203' => UNISEX,
    '3.5" Button (10 pack)' => UNISEX, '204' => UNISEX,
    '3.5" Button (100 pack)' => UNISEX, '205' => UNISEX,
    '38.5 x 24.5 Oval Wall Peel' => UNISEX, '450' => UNISEX,
    '38.5 x 24.5 Wall Peel' => UNISEX, '452' => UNISEX,
    '42x14 Wall Peel' => UNISEX, '454' => UNISEX,
    'Aluminum License Plate' => UNISEX, '495' => UNISEX,
    'Aluminum Oval Keychain' => UNISEX, '494' => UNISEX,
    'Aluminum Photo Keychain' => UNISEX, '493' => UNISEX,
    'Apron' => UNISEX, '42' => UNISEX,
    'Apron (dark)' => UNISEX, '287' => UNISEX,
    'Audio CD' => UNISEX, '93' => UNISEX,
    'Banner' => UNISEX, '208' => UNISEX,
    'Baseball Jersey' => MALE, '38' => MALE,
    'Beach Tote' => UNISEX, '289' => UNISEX,
    'Bib' => UNISEX, '73' => UNISEX,
    'Black Cap' => UNISEX, '65' => UNISEX,
    'Book' => UNISEX, '97' => UNISEX,
    'Boxer Brief' => MALE, '296' => MALE,
    'Boxer Shorts' => MALE, '15' => MALE,
    'Calendar Print' => UNISEX, '74' => UNISEX,
    'Cap' => UNISEX, '140' => UNISEX,
    'Ceramic Travel Mug' => UNISEX, '220' => UNISEX,
    'Charm Bracelet, One Charm' => FEMALE, '488' => FEMALE,
    'Christmas Stocking' => UNISEX, '434' => UNISEX,
    'Classic Thong' => FEMALE, '80' => FEMALE,
    'Customized Felt Christmas Stocking' => UNISEX, '435' => UNISEX,
    'Dark T-Shirt' => MALE, '152' => MALE,
    'Data CD' => UNISEX, '94' => UNISEX,
    'Denim Shirt' => MALE, '217' => MALE,
    'Dog T-Shirt' => UNISEX, '110' => UNISEX,
    'Earring Circle Charm' => FEMALE, '490' => FEMALE,
    'Earring Heart Charm' => FEMALE, '492' => FEMALE,
    'Earring Oval Charm' => FEMALE, '489' => FEMALE,
    'Fathead Wall Graphic' => UNISEX, '502' => UNISEX,
    'Fitted T-Shirt' => MALE, '106' => MALE,
    'Framed Tile' => UNISEX, '147' => UNISEX,
    'Golf Shirt' => MALE, '45' => MALE,
    'Green T-Shirt' => MALE, '108' => MALE,
    'Greeting Card' => UNISEX, '192' => UNISEX,
    'Greeting Cards (Pk of 10)' => UNISEX, '78' => UNISEX,
    'Greeting Cards (Pk of 20)' => UNISEX, '193' => UNISEX,
    'Gym Bag' => UNISEX, '288' => UNISEX,
    'Hooded Sweatshirt' => MALE, '23' => MALE,
    'Hoodie (dark)' => MALE, '244' => MALE,
    'Infant Bodysuit' => UNISEX, '72' => UNISEX,
    'Infant T-Shirt' => UNISEX, '440' => UNISEX,
    'Journal' => UNISEX, '100' => UNISEX,
    'Jr. Hoodie' => FEMALE, '103' => FEMALE,
    'Jr. Jersey T-Shirt' => FEMALE, '6' => FEMALE,
    'Jr. Raglan' => FEMALE, '102' => FEMALE,
    'Jr. Ringer T-Shirt' => FEMALE, '113' => FEMALE,
    'Jr. Spaghetti Tank' => FEMALE, '96' => FEMALE,
    'Keepsake Box' => UNISEX, '86' => UNISEX,
    'Kid\'s Pajamas' => UNISEX, '501' => UNISEX,
    'Kids Baseball Jersey' => UNISEX, '136' => UNISEX,
    'Kids Dark T-Shirt' => UNISEX, '181' => UNISEX,
    'Kids Hoodie' => UNISEX, '133' => UNISEX,
    'Kids Light T-Shirt' => UNISEX, '70' => UNISEX,
    'Kids Sweatshirt' => UNISEX, '135' => UNISEX,
    'Large Mug ' => UNISEX, '1' => UNISEX,
    'Large Pet Bowl' => UNISEX, '216' => UNISEX,
    'Large Thermos Bottle' => UNISEX, '364' => UNISEX,
    'Large Wall Clock' => UNISEX, '232' => UNISEX,
    'License Plate Frame' => UNISEX, '52' => UNISEX,
    'License Plate Holder' => UNISEX, '496' => UNISEX,
    'Light T-Shirt' => MALE, '7' => MALE,
    'Long Sleeve Dark T-Shirt' => MALE, '155' => MALE,
    'Long Sleeve Infant Bodysuit' => UNISEX, '360' => UNISEX,
    'Long Sleeve Infant T-Shirt' => UNISEX, '361' => UNISEX,
    'Long Sleeve T-Shirt' => MALE, '5' => MALE,
    'Magnet' => UNISEX, '119' => UNISEX,
    'Maternity Dark T-Shirt' => FEMALE, '190' => FEMALE,
    'Maternity T-Shirt' => FEMALE, '189' => FEMALE,
    'Men\'s Dark Pajamas ' => MALE, '497' => MALE,
    'Men\'s Fitted T-Shirt (dark)' => MALE, '159' => MALE,
    'Men\'s Light Pajamas ' => MALE, '498' => MALE,
    'Men\'s Performance Jacket' => MALE, '221' => MALE,
    'Men\'s Polo' => MALE, '218' => MALE,
    'Men\'s Sleeveless Tee' => MALE, '115' => MALE,
    'Messenger Bag' => UNISEX, '18' => UNISEX,
    'Military Cap' => UNISEX, '223' => UNISEX,
    'Mini Button' => UNISEX, '141' => UNISEX,
    'Mini Button (10 pack)' => UNISEX, '142' => UNISEX,
    'Mini Button (100 pack)' => UNISEX, '143' => UNISEX,
    'Modern Wall Clock' => UNISEX, '233' => UNISEX,
    'Mousepad ' => UNISEX, '3' => UNISEX,
    'Mug       ' => UNISEX, '0' => UNISEX,
    'Necklace Circle Charm' => FEMALE, '485' => FEMALE,
    'Necklace Heart Charm' => FEMALE, '487' => FEMALE,
    'Necklace Oval Charm' => FEMALE, '486' => FEMALE,
    'Note Cards (Pk of 10)' => UNISEX, '194' => UNISEX,
    'Note Cards (Pk of 20)' => UNISEX, '195' => UNISEX,
    'Organic Baby Bodysuit' => UNISEX, '259' => UNISEX,
    'Organic Baby T-Shirt' => UNISEX, '258' => UNISEX,
    'Organic Kids T-Shirt' => UNISEX, '256' => UNISEX,
    'Organic Kids T-Shirt (dark)' => UNISEX, '257' => UNISEX,
    'Organic Men\'s Fitted T-Shirt' => MALE, '111' => MALE,
    'Organic Men\'s Fitted T-Shirt (dark)' => MALE, '260' => MALE,
    'Organic Men\'s T-Shirt' => MALE, '250' => MALE,
    'Organic Men\'s T-Shirt (dark)' => MALE, '251' => MALE,
    'Organic Toddler T-Shirt' => UNISEX, '261' => UNISEX,
    'Organic Toddler T-Shirt (dark)' => UNISEX, '262' => UNISEX,
    'Organic Women\'s Fitted T-Shirt' => FEMALE, '254' => FEMALE,
    'Organic Women\'s Fitted T-Shirt (dark)' => FEMALE, '255' => FEMALE,
    'Organic Women\'s T-Shirt' => FEMALE, '252' => FEMALE,
    'Organic Women\'s T-Shirt (dark)' => FEMALE, '253' => FEMALE,
    'Ornament (Oval)' => UNISEX, '105' => UNISEX,
    'Ornament (Round)' => UNISEX, '124' => UNISEX,
    'Oversized Wall Calendar' => UNISEX, '162' => UNISEX,
    'Postcards (Package of 8)' => UNISEX, '77' => UNISEX,
    'Rectangle Magnet' => UNISEX, '137' => UNISEX,
    'Rectangle Magnet (10 pack)' => UNISEX, '138' => UNISEX,
    'Rectangle Magnet (100 pack)' => UNISEX, '139' => UNISEX,
    'Ringer T' => MALE, '126' => MALE,
    'Sigg Water Bottle 0.6L' => UNISEX, '281' => UNISEX,
    'Sigg Water Bottle 1.0L' => UNISEX, '280' => UNISEX,
    'Small Pet Bowl' => UNISEX, '215' => UNISEX,
    'Stackable Mug Set (4 mugs)' => UNISEX, '293' => UNISEX,
    'Stadium Blanket' => UNISEX, '368' => UNISEX,
    'Stainless Water Bottle 0.6L' => UNISEX, '358' => UNISEX,
    'Stainless Water Bottle 1.0L' => UNISEX, '359' => UNISEX,
    'Stein' => UNISEX, '359' => UNISEX,
    'Sticker (Bumper 10 pk)' => UNISEX, '209' => UNISEX,
    'Sticker (Bumper 50 pk)' => UNISEX, '210' => UNISEX,
    'Sticker (Bumper)' => UNISEX, '90' => UNISEX,
    'Sticker (Oval 10 pk)' => UNISEX, '211' => UNISEX,
    'Sticker (Oval 50 pk)' => UNISEX, '212' => UNISEX,
    'Sticker (Oval)' => UNISEX, '51' => UNISEX,
    'Sticker (Rectangle 10 pk)' => UNISEX, '213' => UNISEX,
    'Sticker (Rectangle 50 pk)' => UNISEX, '214' => UNISEX,
    'Sticker (Rectangle)' => UNISEX, '50' => UNISEX,
    'Stonewashed Cap' => UNISEX, '224' => UNISEX,
    'Sweatshirt' => MALE, '4' => MALE,
    'Sweatshirt (dark)' => MALE, '249' => MALE,
    'Teddy Bear' => UNISEX, '26' => UNISEX,
    'Thermos Bottle (12oz)' => UNISEX, '366' => UNISEX,
    'Thermos Can Cooler' => UNISEX, '367' => UNISEX,
    'Thermos Food Jar' => UNISEX, '365' => UNISEX,
    'Throw Pillow' => UNISEX, '125' => UNISEX,
    'Tile Coaster' => UNISEX, '37' => UNISEX,
    'Toddler T-Shirt' => UNISEX, '69' => UNISEX,
    'Tote Bag' => UNISEX, '17' => UNISEX,
    'Trek Water Bottle' => UNISEX, '305' => UNISEX,
    'Trucker Hat' => UNISEX, '101' => UNISEX,
    'Value T-shirt' => MALE, '112' => MALE,
    'Vertical Wall Calendar' => UNISEX, '163' => UNISEX,
    'Wall Calendar' => UNISEX, '75' => UNISEX,
    'Wall Clock' => UNISEX, '49' => UNISEX,
    'White T-Shirt' => MALE, '2' => MALE,
    'Women\'s Boy Brief' => FEMALE, '295' => FEMALE,
    'Women\'s Cap Sleeve T-Shirt' => FEMALE, '134' => FEMALE,
    'Women\'s Dark Pajamas ' => FEMALE, '499' => FEMALE,
    'Women\'s Dark T-Shirt' => FEMALE, '161' => FEMALE,
    'Women\'s Fitted T-Shirt (dark)' => FEMALE, '263' => FEMALE,
    'Women\'s Light Pajamas ' => FEMALE, '500' => FEMALE,
    'Women\'s Light T-Shirt' => FEMALE, '109' => FEMALE,
    'Women\'s Long Sleeve Dark T-Shirt' => FEMALE, '164' => FEMALE,
    'Women\'s Long Sleeve T-Shirt' => FEMALE, '165' => FEMALE,
    'Women\'s Performance Jacket' => FEMALE, '222' => FEMALE,
    'Women\'s Plus Size Scoop Neck Dark T-Shirt' => FEMALE, '184' => FEMALE,
    'Women\'s Plus Size Scoop Neck T-Shirt' => FEMALE, '183' => FEMALE,
    'Women\'s Plus Size V-Neck Dark T-Shirt' => FEMALE, '186' => FEMALE,
    'Women\'s Plus Size V-Neck T-Shirt' => FEMALE, '185' => FEMALE,
    'Women\'s Polo' => FEMALE, '219' => FEMALE,
    'Women\'s Raglan Hoodie' => FEMALE, '128' => FEMALE,
    'Women\'s T-Shirt' => FEMALE, '89' => FEMALE,
    'Women\'s Tank Top' => FEMALE, '114' => FEMALE,
    'Women\'s Tracksuit' => FEMALE, '129' => FEMALE,
    'Women\'s V-Neck Dark T-Shirt' => FEMALE, '167' => FEMALE,
    'Women\'s V-Neck T-Shirt' => FEMALE, '166' => FEMALE,
    'Women\'s Zip Hoodie' => FEMALE, '247' => FEMALE,
    'Yard Sign' => UNISEX, '206' => UNISEX,
    'Yellow T-Shirt' => MALE, '107' => MALE,
    'Zip Hoodie' => MALE, '245' => MALE,
    'Zip Hoodie (dark)' => MALE, '246' => MALE,
    'baby blanket' => UNISEX, '363' => UNISEX,
    'baby hat' => UNISEX, '362' => UNISEX,
    'iPad 5-in-1 Case' => UNISEX, '460' => UNISEX,
    'iPad Case' => UNISEX, '459' => UNISEX,
    'iPhone 3G Hard Case' => UNISEX, '441' => UNISEX,
    'iPhone 4 Clear Case' => UNISEX, '444' => UNISEX,
    'iPhone 4 Slider Case' => UNISEX, '443' => UNISEX
  }
end